---
abstract: 'Validate Japanese phone numbers'
author:
  - 'Koichi Taniguchi (a.k.a. nipotan) <taniguchi@livedoor.jp>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Number-Phone-JP
no_index:
  directory:
    - inc
    - share
    - t
requires:
  UNIVERSAL::require: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/nipotan/p5-Number-Phone-JP.git
version: 0.20100104
